apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      project: swiggy
  template:
    metadata:
      labels:
        project: swiggy
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/mygame
          volumeMounts:
            - name: volume-1
              mountPath: "/etc/docker"
      volumes:
        - name: volume-1
          emptyDir: {}
